name: CI
on: [push]
jobs:
  black-linter:
    name: Black Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: black linting
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
  flake8-lint:
    name: flake8 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
